apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  selector:
    matchLabels:
      service: reverseproxy
  replicas: 2
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
        - name: reverseproxy
          image: vidiep2810/reverseproxy:v1
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
      restartPolicy: Always